Architecture:
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Head:
    head_list:
    - CTCHead:
        Head:
          fc_decay: 1.0e-05
        Neck:
          depth: 2
          dims: 120
          hidden_dims: 120
          kernel_size:
          - 1
          - 3
          name: svtr
          use_guide: true
    - NRTRHead:
        max_text_length: 25
        nrtr_dim: 384
    name: MultiHead
  Transform: null
  algorithm: SVTR_LCNet
  model_type: rec
Eval:
  dataset:
    data_dir: c:/Users/spfactz/AndroidStudioProjects/visionbridge/ocr-training/data/
    label_file_list:
    - c:/Users/spfactz/AndroidStudioProjects/visionbridge/ocr-training/data/real_val.txt
    name: SimpleDataSet
    transforms:
    - DecodeImage:
        channel_first: false
        img_mode: BGR
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    batch_size_per_card: 32
    drop_last: false
    num_workers: 0
    shuffle: true
Global:
  cal_metric_during_train: true
  character_dict_path: c:/Users/spfactz/AndroidStudioProjects/visionbridge/ocr-training/PaddleOCR/ppocr/utils/dict/ppocrv5_en_dict.txt
  checkpoints: null
  d2s_train_image_shape:
  - 3
  - 48
  - 320
  debug: false
  distributed: false
  epoch_num: 8
  eval_batch_step:
  - 0
  - 255
  infer_img: null
  infer_mode: false
  log_smooth_window: 20
  max_text_length: 25
  model_name: en_PP-OCRv5_mobile_rec
  pretrained_model: c:/Users/spfactz/AndroidStudioProjects/visionbridge/ocr-training/models/en_PP-OCRv5_mobile_rec_pretrained
  print_batch_step: 10
  save_epoch_step: 1
  save_inference_dir: null
  save_model_dir: c:/Users/spfactz/AndroidStudioProjects/visionbridge/ocr-training/output/vb_en_rec
  save_res_path: ./output/rec/predicts_en_ppocrv5.txt
  use_gpu: false
  use_space_char: true
  use_visualdl: false
Loss:
  loss_config_list:
  - CTCLoss: null
  - NRTRLoss: null
  name: MultiLoss
Metric:
  ignore_space: false
  main_indicator: acc
  name: RecMetric
Optimizer:
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0002
    name: Cosine
    warmup_epoch: 1
  name: Adam
  regularizer:
    factor: 3.0e-05
    name: L2
PostProcess:
  name: CTCLabelDecode
Train:
  dataset:
    data_dir: c:/Users/spfactz/AndroidStudioProjects/visionbridge/ocr-training/data/
    ds_width: false
    ext_op_transform_idx: 1
    label_file_list:
    - c:/Users/spfactz/AndroidStudioProjects/visionbridge/ocr-training/data/train_all.txt
    name: MultiScaleDataSet
    transforms:
    - DecodeImage:
        channel_first: false
        img_mode: BGR
    - RecConAug:
        ext_data_num: 2
        image_shape:
        - 48
        - 320
        - 3
        max_text_length: 25
        prob: 0.5
    - RecAug: null
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    batch_size_per_card: 32
    drop_last: true
    num_workers: 0
    shuffle: true
  sampler:
    divided_factor:
    - 8
    - 16
    first_bs: 32
    fix_bs: false
    is_training: true
    name: MultiScaleSampler
    scales:
    - - 320
      - 32
    - - 320
      - 48
    - - 320
      - 64
